server:
  port: 9090
spring:
  application:
    name: local-grpc-client
grpc:
  client:
    local-grpc-server:
      host:
        - 127.0.0.1
      port:
        - 8989
      enableKeepAlive: true
      keepAliveWithoutCalls: true
