// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package com.lidaifeng.grpc.lib;

public final class GreeterOuterClass {
  private GreeterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ThinkivePortfolioSubmitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ThinkivePortfolioSubmitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ThinkivePortfolioSubmitResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ThinkivePortfolioSubmitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ThinkivePortfolioCommentExamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ThinkivePortfolioCommentExamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ThinkivePortfolioCommentExamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ThinkivePortfolioCommentExamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rgreeter.proto\"\034\n\014HelloRequest\022\014\n\004name\030" +
      "\001 \001(\t\"\035\n\nHelloReply\022\017\n\007message\030\001 \001(\t\"\250\002\n" +
      "\036ThinkivePortfolioSubmitRequest\022\020\n\006funcN" +
      "o\030\001 \001(\tH\000\022\025\n\013portfolioId\030\002 \001(\tH\001\022\023\n\tprod" +
      "uctId\030\003 \001(\tH\002\022\022\n\010investNo\030\004 \001(\tH\003\022\022\n\ninv" +
      "estDesc\030\005 \001(\t\022\025\n\rportfolioName\030\006 \001(\t\022\025\n\r" +
      "portfolioDesc\030\007 \001(\t\022\024\n\014operatorType\030\010 \001(" +
      "\t\022\022\n\nexpireDate\030\t \001(\tB\016\n\014check_funcNoB\023\n" +
      "\021check_portfolioIdB\021\n\017check_productIdB\020\n" +
      "\016check_investNo\"=\n\037ThinkivePortfolioSubm" +
      "itResponse\022\014\n\004code\030\001 \001(\005\022\014\n\004note\030\002 \001(\t\"\244" +
      "\001\n#ThinkivePortfolioCommentExamRequest\022\020" +
      "\n\006funcNo\030\001 \001(\tH\000\022\032\n\020serviceContentId\030\002 \001" +
      "(\tH\001\022\021\n\texamState\030\003 \001(\t\022\022\n\nexamReason\030\004 " +
      "\001(\tB\016\n\014check_funcNoB\030\n\026check_serviceCont" +
      "entId\"B\n$ThinkivePortfolioCommentExamRes" +
      "ponse\022\014\n\004code\030\001 \001(\005\022\014\n\004note\030\002 \001(\t2\202\002\n\007Gr" +
      "eeter\022(\n\010SayHello\022\r.HelloRequest\032\013.Hello" +
      "Reply\"\000\022^\n\027ThinkivePortfolioSubmit\022\037.Thi" +
      "nkivePortfolioSubmitRequest\032 .ThinkivePo" +
      "rtfolioSubmitResponse\"\000\022m\n\034ThinkivePortf" +
      "olioCommentExam\022$.ThinkivePortfolioComme" +
      "ntExamRequest\032%.ThinkivePortfolioComment" +
      "ExamResponse\"\000B\032\n\026com.lidaifeng.grpc.lib" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_ThinkivePortfolioSubmitRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ThinkivePortfolioSubmitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ThinkivePortfolioSubmitRequest_descriptor,
        new java.lang.String[] { "FuncNo", "PortfolioId", "ProductId", "InvestNo", "InvestDesc", "PortfolioName", "PortfolioDesc", "OperatorType", "ExpireDate", "CheckFuncNo", "CheckPortfolioId", "CheckProductId", "CheckInvestNo", });
    internal_static_ThinkivePortfolioSubmitResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ThinkivePortfolioSubmitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ThinkivePortfolioSubmitResponse_descriptor,
        new java.lang.String[] { "Code", "Note", });
    internal_static_ThinkivePortfolioCommentExamRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ThinkivePortfolioCommentExamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ThinkivePortfolioCommentExamRequest_descriptor,
        new java.lang.String[] { "FuncNo", "ServiceContentId", "ExamState", "ExamReason", "CheckFuncNo", "CheckServiceContentId", });
    internal_static_ThinkivePortfolioCommentExamResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ThinkivePortfolioCommentExamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ThinkivePortfolioCommentExamResponse_descriptor,
        new java.lang.String[] { "Code", "Note", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
