// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package com.lidaifeng.grpc.lib;

public interface ThinkivePortfolioCommentExamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ThinkivePortfolioCommentExamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *返回值
   * </pre>
   *
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <pre>
   *返回消息
   * </pre>
   *
   * <code>string note = 2;</code>
   */
  java.lang.String getNote();
  /**
   * <pre>
   *返回消息
   * </pre>
   *
   * <code>string note = 2;</code>
   */
  com.google.protobuf.ByteString
      getNoteBytes();
}
