// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package com.lidaifeng.grpc.lib;

public interface ThinkivePortfolioCommentExamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ThinkivePortfolioCommentExamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *功能号
   * </pre>
   *
   * <code>string funcNo = 1;</code>
   */
  java.lang.String getFuncNo();
  /**
   * <pre>
   *功能号
   * </pre>
   *
   * <code>string funcNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getFuncNoBytes();

  /**
   * <pre>
   *服务内容id
   * </pre>
   *
   * <code>string serviceContentId = 2;</code>
   */
  java.lang.String getServiceContentId();
  /**
   * <pre>
   *服务内容id
   * </pre>
   *
   * <code>string serviceContentId = 2;</code>
   */
  com.google.protobuf.ByteString
      getServiceContentIdBytes();

  /**
   * <pre>
   *审核状态
   * </pre>
   *
   * <code>string examState = 3;</code>
   */
  java.lang.String getExamState();
  /**
   * <pre>
   *审核状态
   * </pre>
   *
   * <code>string examState = 3;</code>
   */
  com.google.protobuf.ByteString
      getExamStateBytes();

  /**
   * <pre>
   *审核原因
   * </pre>
   *
   * <code>string examReason = 4;</code>
   */
  java.lang.String getExamReason();
  /**
   * <pre>
   *审核原因
   * </pre>
   *
   * <code>string examReason = 4;</code>
   */
  com.google.protobuf.ByteString
      getExamReasonBytes();

  public com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest.CheckFuncNoCase getCheckFuncNoCase();

  public com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest.CheckServiceContentIdCase getCheckServiceContentIdCase();
}
