// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package com.lidaifeng.grpc.lib;

public interface ThinkivePortfolioSubmitRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ThinkivePortfolioSubmitRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *功能号
   * </pre>
   *
   * <code>string funcNo = 1;</code>
   */
  java.lang.String getFuncNo();
  /**
   * <pre>
   *功能号
   * </pre>
   *
   * <code>string funcNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getFuncNoBytes();

  /**
   * <pre>
   *组合id
   * </pre>
   *
   * <code>string portfolioId = 2;</code>
   */
  java.lang.String getPortfolioId();
  /**
   * <pre>
   *组合id
   * </pre>
   *
   * <code>string portfolioId = 2;</code>
   */
  com.google.protobuf.ByteString
      getPortfolioIdBytes();

  /**
   * <pre>
   *产品id
   * </pre>
   *
   * <code>string productId = 3;</code>
   */
  java.lang.String getProductId();
  /**
   * <pre>
   *产品id
   * </pre>
   *
   * <code>string productId = 3;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <pre>
   *投顾号
   * </pre>
   *
   * <code>string investNo = 4;</code>
   */
  java.lang.String getInvestNo();
  /**
   * <pre>
   *投顾号
   * </pre>
   *
   * <code>string investNo = 4;</code>
   */
  com.google.protobuf.ByteString
      getInvestNoBytes();

  /**
   * <pre>
   *投顾介绍
   * </pre>
   *
   * <code>string investDesc = 5;</code>
   */
  java.lang.String getInvestDesc();
  /**
   * <pre>
   *投顾介绍
   * </pre>
   *
   * <code>string investDesc = 5;</code>
   */
  com.google.protobuf.ByteString
      getInvestDescBytes();

  /**
   * <pre>
   *组合名称
   * </pre>
   *
   * <code>string portfolioName = 6;</code>
   */
  java.lang.String getPortfolioName();
  /**
   * <pre>
   *组合名称
   * </pre>
   *
   * <code>string portfolioName = 6;</code>
   */
  com.google.protobuf.ByteString
      getPortfolioNameBytes();

  /**
   * <pre>
   *组合描述
   * </pre>
   *
   * <code>string portfolioDesc = 7;</code>
   */
  java.lang.String getPortfolioDesc();
  /**
   * <pre>
   *组合描述
   * </pre>
   *
   * <code>string portfolioDesc = 7;</code>
   */
  com.google.protobuf.ByteString
      getPortfolioDescBytes();

  /**
   * <pre>
   *操作类型
   * </pre>
   *
   * <code>string operatorType = 8;</code>
   */
  java.lang.String getOperatorType();
  /**
   * <pre>
   *操作类型
   * </pre>
   *
   * <code>string operatorType = 8;</code>
   */
  com.google.protobuf.ByteString
      getOperatorTypeBytes();

  /**
   * <pre>
   *时间
   * </pre>
   *
   * <code>string expireDate = 9;</code>
   */
  java.lang.String getExpireDate();
  /**
   * <pre>
   *时间
   * </pre>
   *
   * <code>string expireDate = 9;</code>
   */
  com.google.protobuf.ByteString
      getExpireDateBytes();

  public com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest.CheckFuncNoCase getCheckFuncNoCase();

  public com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest.CheckPortfolioIdCase getCheckPortfolioIdCase();

  public com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest.CheckProductIdCase getCheckProductIdCase();

  public com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest.CheckInvestNoCase getCheckInvestNoCase();
}
