// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package com.lidaifeng.grpc.lib;

/**
 * Protobuf type {@code ThinkivePortfolioCommentExamRequest}
 */
public  final class ThinkivePortfolioCommentExamRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ThinkivePortfolioCommentExamRequest)
    ThinkivePortfolioCommentExamRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ThinkivePortfolioCommentExamRequest.newBuilder() to construct.
  private ThinkivePortfolioCommentExamRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ThinkivePortfolioCommentExamRequest() {
    examState_ = "";
    examReason_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ThinkivePortfolioCommentExamRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            checkFuncNoCase_ = 1;
            checkFuncNo_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            checkServiceContentIdCase_ = 2;
            checkServiceContentId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            examState_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            examReason_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lidaifeng.grpc.lib.GreeterOuterClass.internal_static_ThinkivePortfolioCommentExamRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lidaifeng.grpc.lib.GreeterOuterClass.internal_static_ThinkivePortfolioCommentExamRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest.class, com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest.Builder.class);
  }

  private int checkFuncNoCase_ = 0;
  private java.lang.Object checkFuncNo_;
  public enum CheckFuncNoCase
      implements com.google.protobuf.Internal.EnumLite {
    FUNCNO(1),
    CHECKFUNCNO_NOT_SET(0);
    private final int value;
    private CheckFuncNoCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CheckFuncNoCase valueOf(int value) {
      return forNumber(value);
    }

    public static CheckFuncNoCase forNumber(int value) {
      switch (value) {
        case 1: return FUNCNO;
        case 0: return CHECKFUNCNO_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public CheckFuncNoCase
  getCheckFuncNoCase() {
    return CheckFuncNoCase.forNumber(
        checkFuncNoCase_);
  }

  private int checkServiceContentIdCase_ = 0;
  private java.lang.Object checkServiceContentId_;
  public enum CheckServiceContentIdCase
      implements com.google.protobuf.Internal.EnumLite {
    SERVICECONTENTID(2),
    CHECKSERVICECONTENTID_NOT_SET(0);
    private final int value;
    private CheckServiceContentIdCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CheckServiceContentIdCase valueOf(int value) {
      return forNumber(value);
    }

    public static CheckServiceContentIdCase forNumber(int value) {
      switch (value) {
        case 2: return SERVICECONTENTID;
        case 0: return CHECKSERVICECONTENTID_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public CheckServiceContentIdCase
  getCheckServiceContentIdCase() {
    return CheckServiceContentIdCase.forNumber(
        checkServiceContentIdCase_);
  }

  public static final int FUNCNO_FIELD_NUMBER = 1;
  /**
   * <pre>
   *功能号
   * </pre>
   *
   * <code>string funcNo = 1;</code>
   */
  public java.lang.String getFuncNo() {
    java.lang.Object ref = "";
    if (checkFuncNoCase_ == 1) {
      ref = checkFuncNo_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (checkFuncNoCase_ == 1) {
        checkFuncNo_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   *功能号
   * </pre>
   *
   * <code>string funcNo = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFuncNoBytes() {
    java.lang.Object ref = "";
    if (checkFuncNoCase_ == 1) {
      ref = checkFuncNo_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (checkFuncNoCase_ == 1) {
        checkFuncNo_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICECONTENTID_FIELD_NUMBER = 2;
  /**
   * <pre>
   *服务内容id
   * </pre>
   *
   * <code>string serviceContentId = 2;</code>
   */
  public java.lang.String getServiceContentId() {
    java.lang.Object ref = "";
    if (checkServiceContentIdCase_ == 2) {
      ref = checkServiceContentId_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (checkServiceContentIdCase_ == 2) {
        checkServiceContentId_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   *服务内容id
   * </pre>
   *
   * <code>string serviceContentId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getServiceContentIdBytes() {
    java.lang.Object ref = "";
    if (checkServiceContentIdCase_ == 2) {
      ref = checkServiceContentId_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (checkServiceContentIdCase_ == 2) {
        checkServiceContentId_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXAMSTATE_FIELD_NUMBER = 3;
  private volatile java.lang.Object examState_;
  /**
   * <pre>
   *审核状态
   * </pre>
   *
   * <code>string examState = 3;</code>
   */
  public java.lang.String getExamState() {
    java.lang.Object ref = examState_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      examState_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *审核状态
   * </pre>
   *
   * <code>string examState = 3;</code>
   */
  public com.google.protobuf.ByteString
      getExamStateBytes() {
    java.lang.Object ref = examState_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      examState_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXAMREASON_FIELD_NUMBER = 4;
  private volatile java.lang.Object examReason_;
  /**
   * <pre>
   *审核原因
   * </pre>
   *
   * <code>string examReason = 4;</code>
   */
  public java.lang.String getExamReason() {
    java.lang.Object ref = examReason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      examReason_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *审核原因
   * </pre>
   *
   * <code>string examReason = 4;</code>
   */
  public com.google.protobuf.ByteString
      getExamReasonBytes() {
    java.lang.Object ref = examReason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      examReason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (checkFuncNoCase_ == 1) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, checkFuncNo_);
    }
    if (checkServiceContentIdCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, checkServiceContentId_);
    }
    if (!getExamStateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, examState_);
    }
    if (!getExamReasonBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, examReason_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (checkFuncNoCase_ == 1) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, checkFuncNo_);
    }
    if (checkServiceContentIdCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, checkServiceContentId_);
    }
    if (!getExamStateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, examState_);
    }
    if (!getExamReasonBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, examReason_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest)) {
      return super.equals(obj);
    }
    com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest other = (com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest) obj;

    boolean result = true;
    result = result && getExamState()
        .equals(other.getExamState());
    result = result && getExamReason()
        .equals(other.getExamReason());
    result = result && getCheckFuncNoCase().equals(
        other.getCheckFuncNoCase());
    if (!result) return false;
    switch (checkFuncNoCase_) {
      case 1:
        result = result && getFuncNo()
            .equals(other.getFuncNo());
        break;
      case 0:
      default:
    }
    result = result && getCheckServiceContentIdCase().equals(
        other.getCheckServiceContentIdCase());
    if (!result) return false;
    switch (checkServiceContentIdCase_) {
      case 2:
        result = result && getServiceContentId()
            .equals(other.getServiceContentId());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXAMSTATE_FIELD_NUMBER;
    hash = (53 * hash) + getExamState().hashCode();
    hash = (37 * hash) + EXAMREASON_FIELD_NUMBER;
    hash = (53 * hash) + getExamReason().hashCode();
    switch (checkFuncNoCase_) {
      case 1:
        hash = (37 * hash) + FUNCNO_FIELD_NUMBER;
        hash = (53 * hash) + getFuncNo().hashCode();
        break;
      case 0:
      default:
    }
    switch (checkServiceContentIdCase_) {
      case 2:
        hash = (37 * hash) + SERVICECONTENTID_FIELD_NUMBER;
        hash = (53 * hash) + getServiceContentId().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ThinkivePortfolioCommentExamRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ThinkivePortfolioCommentExamRequest)
      com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lidaifeng.grpc.lib.GreeterOuterClass.internal_static_ThinkivePortfolioCommentExamRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lidaifeng.grpc.lib.GreeterOuterClass.internal_static_ThinkivePortfolioCommentExamRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest.class, com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest.Builder.class);
    }

    // Construct using com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      examState_ = "";

      examReason_ = "";

      checkFuncNoCase_ = 0;
      checkFuncNo_ = null;
      checkServiceContentIdCase_ = 0;
      checkServiceContentId_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lidaifeng.grpc.lib.GreeterOuterClass.internal_static_ThinkivePortfolioCommentExamRequest_descriptor;
    }

    @java.lang.Override
    public com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest getDefaultInstanceForType() {
      return com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest build() {
      com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest buildPartial() {
      com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest result = new com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest(this);
      if (checkFuncNoCase_ == 1) {
        result.checkFuncNo_ = checkFuncNo_;
      }
      if (checkServiceContentIdCase_ == 2) {
        result.checkServiceContentId_ = checkServiceContentId_;
      }
      result.examState_ = examState_;
      result.examReason_ = examReason_;
      result.checkFuncNoCase_ = checkFuncNoCase_;
      result.checkServiceContentIdCase_ = checkServiceContentIdCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest) {
        return mergeFrom((com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest other) {
      if (other == com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest.getDefaultInstance()) return this;
      if (!other.getExamState().isEmpty()) {
        examState_ = other.examState_;
        onChanged();
      }
      if (!other.getExamReason().isEmpty()) {
        examReason_ = other.examReason_;
        onChanged();
      }
      switch (other.getCheckFuncNoCase()) {
        case FUNCNO: {
          checkFuncNoCase_ = 1;
          checkFuncNo_ = other.checkFuncNo_;
          onChanged();
          break;
        }
        case CHECKFUNCNO_NOT_SET: {
          break;
        }
      }
      switch (other.getCheckServiceContentIdCase()) {
        case SERVICECONTENTID: {
          checkServiceContentIdCase_ = 2;
          checkServiceContentId_ = other.checkServiceContentId_;
          onChanged();
          break;
        }
        case CHECKSERVICECONTENTID_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int checkFuncNoCase_ = 0;
    private java.lang.Object checkFuncNo_;
    public CheckFuncNoCase
        getCheckFuncNoCase() {
      return CheckFuncNoCase.forNumber(
          checkFuncNoCase_);
    }

    public Builder clearCheckFuncNo() {
      checkFuncNoCase_ = 0;
      checkFuncNo_ = null;
      onChanged();
      return this;
    }

    private int checkServiceContentIdCase_ = 0;
    private java.lang.Object checkServiceContentId_;
    public CheckServiceContentIdCase
        getCheckServiceContentIdCase() {
      return CheckServiceContentIdCase.forNumber(
          checkServiceContentIdCase_);
    }

    public Builder clearCheckServiceContentId() {
      checkServiceContentIdCase_ = 0;
      checkServiceContentId_ = null;
      onChanged();
      return this;
    }


    /**
     * <pre>
     *功能号
     * </pre>
     *
     * <code>string funcNo = 1;</code>
     */
    public java.lang.String getFuncNo() {
      java.lang.Object ref = "";
      if (checkFuncNoCase_ == 1) {
        ref = checkFuncNo_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (checkFuncNoCase_ == 1) {
          checkFuncNo_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *功能号
     * </pre>
     *
     * <code>string funcNo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFuncNoBytes() {
      java.lang.Object ref = "";
      if (checkFuncNoCase_ == 1) {
        ref = checkFuncNo_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (checkFuncNoCase_ == 1) {
          checkFuncNo_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *功能号
     * </pre>
     *
     * <code>string funcNo = 1;</code>
     */
    public Builder setFuncNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkFuncNoCase_ = 1;
      checkFuncNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *功能号
     * </pre>
     *
     * <code>string funcNo = 1;</code>
     */
    public Builder clearFuncNo() {
      if (checkFuncNoCase_ == 1) {
        checkFuncNoCase_ = 0;
        checkFuncNo_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     *功能号
     * </pre>
     *
     * <code>string funcNo = 1;</code>
     */
    public Builder setFuncNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      checkFuncNoCase_ = 1;
      checkFuncNo_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     *服务内容id
     * </pre>
     *
     * <code>string serviceContentId = 2;</code>
     */
    public java.lang.String getServiceContentId() {
      java.lang.Object ref = "";
      if (checkServiceContentIdCase_ == 2) {
        ref = checkServiceContentId_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (checkServiceContentIdCase_ == 2) {
          checkServiceContentId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *服务内容id
     * </pre>
     *
     * <code>string serviceContentId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServiceContentIdBytes() {
      java.lang.Object ref = "";
      if (checkServiceContentIdCase_ == 2) {
        ref = checkServiceContentId_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (checkServiceContentIdCase_ == 2) {
          checkServiceContentId_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *服务内容id
     * </pre>
     *
     * <code>string serviceContentId = 2;</code>
     */
    public Builder setServiceContentId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkServiceContentIdCase_ = 2;
      checkServiceContentId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *服务内容id
     * </pre>
     *
     * <code>string serviceContentId = 2;</code>
     */
    public Builder clearServiceContentId() {
      if (checkServiceContentIdCase_ == 2) {
        checkServiceContentIdCase_ = 0;
        checkServiceContentId_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     *服务内容id
     * </pre>
     *
     * <code>string serviceContentId = 2;</code>
     */
    public Builder setServiceContentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      checkServiceContentIdCase_ = 2;
      checkServiceContentId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object examState_ = "";
    /**
     * <pre>
     *审核状态
     * </pre>
     *
     * <code>string examState = 3;</code>
     */
    public java.lang.String getExamState() {
      java.lang.Object ref = examState_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        examState_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *审核状态
     * </pre>
     *
     * <code>string examState = 3;</code>
     */
    public com.google.protobuf.ByteString
        getExamStateBytes() {
      java.lang.Object ref = examState_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        examState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *审核状态
     * </pre>
     *
     * <code>string examState = 3;</code>
     */
    public Builder setExamState(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      examState_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *审核状态
     * </pre>
     *
     * <code>string examState = 3;</code>
     */
    public Builder clearExamState() {
      
      examState_ = getDefaultInstance().getExamState();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *审核状态
     * </pre>
     *
     * <code>string examState = 3;</code>
     */
    public Builder setExamStateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      examState_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object examReason_ = "";
    /**
     * <pre>
     *审核原因
     * </pre>
     *
     * <code>string examReason = 4;</code>
     */
    public java.lang.String getExamReason() {
      java.lang.Object ref = examReason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        examReason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *审核原因
     * </pre>
     *
     * <code>string examReason = 4;</code>
     */
    public com.google.protobuf.ByteString
        getExamReasonBytes() {
      java.lang.Object ref = examReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        examReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *审核原因
     * </pre>
     *
     * <code>string examReason = 4;</code>
     */
    public Builder setExamReason(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      examReason_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *审核原因
     * </pre>
     *
     * <code>string examReason = 4;</code>
     */
    public Builder clearExamReason() {
      
      examReason_ = getDefaultInstance().getExamReason();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *审核原因
     * </pre>
     *
     * <code>string examReason = 4;</code>
     */
    public Builder setExamReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      examReason_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ThinkivePortfolioCommentExamRequest)
  }

  // @@protoc_insertion_point(class_scope:ThinkivePortfolioCommentExamRequest)
  private static final com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest();
  }

  public static com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ThinkivePortfolioCommentExamRequest>
      PARSER = new com.google.protobuf.AbstractParser<ThinkivePortfolioCommentExamRequest>() {
    @java.lang.Override
    public ThinkivePortfolioCommentExamRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ThinkivePortfolioCommentExamRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ThinkivePortfolioCommentExamRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ThinkivePortfolioCommentExamRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lidaifeng.grpc.lib.ThinkivePortfolioCommentExamRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

