// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package com.lidaifeng.grpc.lib;

/**
 * Protobuf type {@code ThinkivePortfolioSubmitRequest}
 */
public  final class ThinkivePortfolioSubmitRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ThinkivePortfolioSubmitRequest)
    ThinkivePortfolioSubmitRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ThinkivePortfolioSubmitRequest.newBuilder() to construct.
  private ThinkivePortfolioSubmitRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ThinkivePortfolioSubmitRequest() {
    investDesc_ = "";
    portfolioName_ = "";
    portfolioDesc_ = "";
    operatorType_ = "";
    expireDate_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ThinkivePortfolioSubmitRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            checkFuncNoCase_ = 1;
            checkFuncNo_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            checkPortfolioIdCase_ = 2;
            checkPortfolioId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            checkProductIdCase_ = 3;
            checkProductId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            checkInvestNoCase_ = 4;
            checkInvestNo_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            investDesc_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            portfolioName_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            portfolioDesc_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            operatorType_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            expireDate_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lidaifeng.grpc.lib.GreeterOuterClass.internal_static_ThinkivePortfolioSubmitRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lidaifeng.grpc.lib.GreeterOuterClass.internal_static_ThinkivePortfolioSubmitRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest.class, com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest.Builder.class);
  }

  private int checkFuncNoCase_ = 0;
  private java.lang.Object checkFuncNo_;
  public enum CheckFuncNoCase
      implements com.google.protobuf.Internal.EnumLite {
    FUNCNO(1),
    CHECKFUNCNO_NOT_SET(0);
    private final int value;
    private CheckFuncNoCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CheckFuncNoCase valueOf(int value) {
      return forNumber(value);
    }

    public static CheckFuncNoCase forNumber(int value) {
      switch (value) {
        case 1: return FUNCNO;
        case 0: return CHECKFUNCNO_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public CheckFuncNoCase
  getCheckFuncNoCase() {
    return CheckFuncNoCase.forNumber(
        checkFuncNoCase_);
  }

  private int checkPortfolioIdCase_ = 0;
  private java.lang.Object checkPortfolioId_;
  public enum CheckPortfolioIdCase
      implements com.google.protobuf.Internal.EnumLite {
    PORTFOLIOID(2),
    CHECKPORTFOLIOID_NOT_SET(0);
    private final int value;
    private CheckPortfolioIdCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CheckPortfolioIdCase valueOf(int value) {
      return forNumber(value);
    }

    public static CheckPortfolioIdCase forNumber(int value) {
      switch (value) {
        case 2: return PORTFOLIOID;
        case 0: return CHECKPORTFOLIOID_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public CheckPortfolioIdCase
  getCheckPortfolioIdCase() {
    return CheckPortfolioIdCase.forNumber(
        checkPortfolioIdCase_);
  }

  private int checkProductIdCase_ = 0;
  private java.lang.Object checkProductId_;
  public enum CheckProductIdCase
      implements com.google.protobuf.Internal.EnumLite {
    PRODUCTID(3),
    CHECKPRODUCTID_NOT_SET(0);
    private final int value;
    private CheckProductIdCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CheckProductIdCase valueOf(int value) {
      return forNumber(value);
    }

    public static CheckProductIdCase forNumber(int value) {
      switch (value) {
        case 3: return PRODUCTID;
        case 0: return CHECKPRODUCTID_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public CheckProductIdCase
  getCheckProductIdCase() {
    return CheckProductIdCase.forNumber(
        checkProductIdCase_);
  }

  private int checkInvestNoCase_ = 0;
  private java.lang.Object checkInvestNo_;
  public enum CheckInvestNoCase
      implements com.google.protobuf.Internal.EnumLite {
    INVESTNO(4),
    CHECKINVESTNO_NOT_SET(0);
    private final int value;
    private CheckInvestNoCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CheckInvestNoCase valueOf(int value) {
      return forNumber(value);
    }

    public static CheckInvestNoCase forNumber(int value) {
      switch (value) {
        case 4: return INVESTNO;
        case 0: return CHECKINVESTNO_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public CheckInvestNoCase
  getCheckInvestNoCase() {
    return CheckInvestNoCase.forNumber(
        checkInvestNoCase_);
  }

  public static final int FUNCNO_FIELD_NUMBER = 1;
  /**
   * <pre>
   *功能号
   * </pre>
   *
   * <code>string funcNo = 1;</code>
   */
  public java.lang.String getFuncNo() {
    java.lang.Object ref = "";
    if (checkFuncNoCase_ == 1) {
      ref = checkFuncNo_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (checkFuncNoCase_ == 1) {
        checkFuncNo_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   *功能号
   * </pre>
   *
   * <code>string funcNo = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFuncNoBytes() {
    java.lang.Object ref = "";
    if (checkFuncNoCase_ == 1) {
      ref = checkFuncNo_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (checkFuncNoCase_ == 1) {
        checkFuncNo_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORTFOLIOID_FIELD_NUMBER = 2;
  /**
   * <pre>
   *组合id
   * </pre>
   *
   * <code>string portfolioId = 2;</code>
   */
  public java.lang.String getPortfolioId() {
    java.lang.Object ref = "";
    if (checkPortfolioIdCase_ == 2) {
      ref = checkPortfolioId_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (checkPortfolioIdCase_ == 2) {
        checkPortfolioId_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   *组合id
   * </pre>
   *
   * <code>string portfolioId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPortfolioIdBytes() {
    java.lang.Object ref = "";
    if (checkPortfolioIdCase_ == 2) {
      ref = checkPortfolioId_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (checkPortfolioIdCase_ == 2) {
        checkPortfolioId_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTID_FIELD_NUMBER = 3;
  /**
   * <pre>
   *产品id
   * </pre>
   *
   * <code>string productId = 3;</code>
   */
  public java.lang.String getProductId() {
    java.lang.Object ref = "";
    if (checkProductIdCase_ == 3) {
      ref = checkProductId_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (checkProductIdCase_ == 3) {
        checkProductId_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   *产品id
   * </pre>
   *
   * <code>string productId = 3;</code>
   */
  public com.google.protobuf.ByteString
      getProductIdBytes() {
    java.lang.Object ref = "";
    if (checkProductIdCase_ == 3) {
      ref = checkProductId_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (checkProductIdCase_ == 3) {
        checkProductId_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INVESTNO_FIELD_NUMBER = 4;
  /**
   * <pre>
   *投顾号
   * </pre>
   *
   * <code>string investNo = 4;</code>
   */
  public java.lang.String getInvestNo() {
    java.lang.Object ref = "";
    if (checkInvestNoCase_ == 4) {
      ref = checkInvestNo_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (checkInvestNoCase_ == 4) {
        checkInvestNo_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   *投顾号
   * </pre>
   *
   * <code>string investNo = 4;</code>
   */
  public com.google.protobuf.ByteString
      getInvestNoBytes() {
    java.lang.Object ref = "";
    if (checkInvestNoCase_ == 4) {
      ref = checkInvestNo_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (checkInvestNoCase_ == 4) {
        checkInvestNo_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INVESTDESC_FIELD_NUMBER = 5;
  private volatile java.lang.Object investDesc_;
  /**
   * <pre>
   *投顾介绍
   * </pre>
   *
   * <code>string investDesc = 5;</code>
   */
  public java.lang.String getInvestDesc() {
    java.lang.Object ref = investDesc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      investDesc_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *投顾介绍
   * </pre>
   *
   * <code>string investDesc = 5;</code>
   */
  public com.google.protobuf.ByteString
      getInvestDescBytes() {
    java.lang.Object ref = investDesc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      investDesc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORTFOLIONAME_FIELD_NUMBER = 6;
  private volatile java.lang.Object portfolioName_;
  /**
   * <pre>
   *组合名称
   * </pre>
   *
   * <code>string portfolioName = 6;</code>
   */
  public java.lang.String getPortfolioName() {
    java.lang.Object ref = portfolioName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      portfolioName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *组合名称
   * </pre>
   *
   * <code>string portfolioName = 6;</code>
   */
  public com.google.protobuf.ByteString
      getPortfolioNameBytes() {
    java.lang.Object ref = portfolioName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      portfolioName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORTFOLIODESC_FIELD_NUMBER = 7;
  private volatile java.lang.Object portfolioDesc_;
  /**
   * <pre>
   *组合描述
   * </pre>
   *
   * <code>string portfolioDesc = 7;</code>
   */
  public java.lang.String getPortfolioDesc() {
    java.lang.Object ref = portfolioDesc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      portfolioDesc_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *组合描述
   * </pre>
   *
   * <code>string portfolioDesc = 7;</code>
   */
  public com.google.protobuf.ByteString
      getPortfolioDescBytes() {
    java.lang.Object ref = portfolioDesc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      portfolioDesc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATORTYPE_FIELD_NUMBER = 8;
  private volatile java.lang.Object operatorType_;
  /**
   * <pre>
   *操作类型
   * </pre>
   *
   * <code>string operatorType = 8;</code>
   */
  public java.lang.String getOperatorType() {
    java.lang.Object ref = operatorType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      operatorType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *操作类型
   * </pre>
   *
   * <code>string operatorType = 8;</code>
   */
  public com.google.protobuf.ByteString
      getOperatorTypeBytes() {
    java.lang.Object ref = operatorType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      operatorType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPIREDATE_FIELD_NUMBER = 9;
  private volatile java.lang.Object expireDate_;
  /**
   * <pre>
   *时间
   * </pre>
   *
   * <code>string expireDate = 9;</code>
   */
  public java.lang.String getExpireDate() {
    java.lang.Object ref = expireDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      expireDate_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *时间
   * </pre>
   *
   * <code>string expireDate = 9;</code>
   */
  public com.google.protobuf.ByteString
      getExpireDateBytes() {
    java.lang.Object ref = expireDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      expireDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (checkFuncNoCase_ == 1) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, checkFuncNo_);
    }
    if (checkPortfolioIdCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, checkPortfolioId_);
    }
    if (checkProductIdCase_ == 3) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, checkProductId_);
    }
    if (checkInvestNoCase_ == 4) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, checkInvestNo_);
    }
    if (!getInvestDescBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, investDesc_);
    }
    if (!getPortfolioNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, portfolioName_);
    }
    if (!getPortfolioDescBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, portfolioDesc_);
    }
    if (!getOperatorTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, operatorType_);
    }
    if (!getExpireDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, expireDate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (checkFuncNoCase_ == 1) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, checkFuncNo_);
    }
    if (checkPortfolioIdCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, checkPortfolioId_);
    }
    if (checkProductIdCase_ == 3) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, checkProductId_);
    }
    if (checkInvestNoCase_ == 4) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, checkInvestNo_);
    }
    if (!getInvestDescBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, investDesc_);
    }
    if (!getPortfolioNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, portfolioName_);
    }
    if (!getPortfolioDescBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, portfolioDesc_);
    }
    if (!getOperatorTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, operatorType_);
    }
    if (!getExpireDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, expireDate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest)) {
      return super.equals(obj);
    }
    com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest other = (com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest) obj;

    boolean result = true;
    result = result && getInvestDesc()
        .equals(other.getInvestDesc());
    result = result && getPortfolioName()
        .equals(other.getPortfolioName());
    result = result && getPortfolioDesc()
        .equals(other.getPortfolioDesc());
    result = result && getOperatorType()
        .equals(other.getOperatorType());
    result = result && getExpireDate()
        .equals(other.getExpireDate());
    result = result && getCheckFuncNoCase().equals(
        other.getCheckFuncNoCase());
    if (!result) return false;
    switch (checkFuncNoCase_) {
      case 1:
        result = result && getFuncNo()
            .equals(other.getFuncNo());
        break;
      case 0:
      default:
    }
    result = result && getCheckPortfolioIdCase().equals(
        other.getCheckPortfolioIdCase());
    if (!result) return false;
    switch (checkPortfolioIdCase_) {
      case 2:
        result = result && getPortfolioId()
            .equals(other.getPortfolioId());
        break;
      case 0:
      default:
    }
    result = result && getCheckProductIdCase().equals(
        other.getCheckProductIdCase());
    if (!result) return false;
    switch (checkProductIdCase_) {
      case 3:
        result = result && getProductId()
            .equals(other.getProductId());
        break;
      case 0:
      default:
    }
    result = result && getCheckInvestNoCase().equals(
        other.getCheckInvestNoCase());
    if (!result) return false;
    switch (checkInvestNoCase_) {
      case 4:
        result = result && getInvestNo()
            .equals(other.getInvestNo());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INVESTDESC_FIELD_NUMBER;
    hash = (53 * hash) + getInvestDesc().hashCode();
    hash = (37 * hash) + PORTFOLIONAME_FIELD_NUMBER;
    hash = (53 * hash) + getPortfolioName().hashCode();
    hash = (37 * hash) + PORTFOLIODESC_FIELD_NUMBER;
    hash = (53 * hash) + getPortfolioDesc().hashCode();
    hash = (37 * hash) + OPERATORTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getOperatorType().hashCode();
    hash = (37 * hash) + EXPIREDATE_FIELD_NUMBER;
    hash = (53 * hash) + getExpireDate().hashCode();
    switch (checkFuncNoCase_) {
      case 1:
        hash = (37 * hash) + FUNCNO_FIELD_NUMBER;
        hash = (53 * hash) + getFuncNo().hashCode();
        break;
      case 0:
      default:
    }
    switch (checkPortfolioIdCase_) {
      case 2:
        hash = (37 * hash) + PORTFOLIOID_FIELD_NUMBER;
        hash = (53 * hash) + getPortfolioId().hashCode();
        break;
      case 0:
      default:
    }
    switch (checkProductIdCase_) {
      case 3:
        hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
        hash = (53 * hash) + getProductId().hashCode();
        break;
      case 0:
      default:
    }
    switch (checkInvestNoCase_) {
      case 4:
        hash = (37 * hash) + INVESTNO_FIELD_NUMBER;
        hash = (53 * hash) + getInvestNo().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ThinkivePortfolioSubmitRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ThinkivePortfolioSubmitRequest)
      com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lidaifeng.grpc.lib.GreeterOuterClass.internal_static_ThinkivePortfolioSubmitRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lidaifeng.grpc.lib.GreeterOuterClass.internal_static_ThinkivePortfolioSubmitRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest.class, com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest.Builder.class);
    }

    // Construct using com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      investDesc_ = "";

      portfolioName_ = "";

      portfolioDesc_ = "";

      operatorType_ = "";

      expireDate_ = "";

      checkFuncNoCase_ = 0;
      checkFuncNo_ = null;
      checkPortfolioIdCase_ = 0;
      checkPortfolioId_ = null;
      checkProductIdCase_ = 0;
      checkProductId_ = null;
      checkInvestNoCase_ = 0;
      checkInvestNo_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lidaifeng.grpc.lib.GreeterOuterClass.internal_static_ThinkivePortfolioSubmitRequest_descriptor;
    }

    @java.lang.Override
    public com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest getDefaultInstanceForType() {
      return com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest build() {
      com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest buildPartial() {
      com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest result = new com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest(this);
      if (checkFuncNoCase_ == 1) {
        result.checkFuncNo_ = checkFuncNo_;
      }
      if (checkPortfolioIdCase_ == 2) {
        result.checkPortfolioId_ = checkPortfolioId_;
      }
      if (checkProductIdCase_ == 3) {
        result.checkProductId_ = checkProductId_;
      }
      if (checkInvestNoCase_ == 4) {
        result.checkInvestNo_ = checkInvestNo_;
      }
      result.investDesc_ = investDesc_;
      result.portfolioName_ = portfolioName_;
      result.portfolioDesc_ = portfolioDesc_;
      result.operatorType_ = operatorType_;
      result.expireDate_ = expireDate_;
      result.checkFuncNoCase_ = checkFuncNoCase_;
      result.checkPortfolioIdCase_ = checkPortfolioIdCase_;
      result.checkProductIdCase_ = checkProductIdCase_;
      result.checkInvestNoCase_ = checkInvestNoCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest) {
        return mergeFrom((com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest other) {
      if (other == com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest.getDefaultInstance()) return this;
      if (!other.getInvestDesc().isEmpty()) {
        investDesc_ = other.investDesc_;
        onChanged();
      }
      if (!other.getPortfolioName().isEmpty()) {
        portfolioName_ = other.portfolioName_;
        onChanged();
      }
      if (!other.getPortfolioDesc().isEmpty()) {
        portfolioDesc_ = other.portfolioDesc_;
        onChanged();
      }
      if (!other.getOperatorType().isEmpty()) {
        operatorType_ = other.operatorType_;
        onChanged();
      }
      if (!other.getExpireDate().isEmpty()) {
        expireDate_ = other.expireDate_;
        onChanged();
      }
      switch (other.getCheckFuncNoCase()) {
        case FUNCNO: {
          checkFuncNoCase_ = 1;
          checkFuncNo_ = other.checkFuncNo_;
          onChanged();
          break;
        }
        case CHECKFUNCNO_NOT_SET: {
          break;
        }
      }
      switch (other.getCheckPortfolioIdCase()) {
        case PORTFOLIOID: {
          checkPortfolioIdCase_ = 2;
          checkPortfolioId_ = other.checkPortfolioId_;
          onChanged();
          break;
        }
        case CHECKPORTFOLIOID_NOT_SET: {
          break;
        }
      }
      switch (other.getCheckProductIdCase()) {
        case PRODUCTID: {
          checkProductIdCase_ = 3;
          checkProductId_ = other.checkProductId_;
          onChanged();
          break;
        }
        case CHECKPRODUCTID_NOT_SET: {
          break;
        }
      }
      switch (other.getCheckInvestNoCase()) {
        case INVESTNO: {
          checkInvestNoCase_ = 4;
          checkInvestNo_ = other.checkInvestNo_;
          onChanged();
          break;
        }
        case CHECKINVESTNO_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int checkFuncNoCase_ = 0;
    private java.lang.Object checkFuncNo_;
    public CheckFuncNoCase
        getCheckFuncNoCase() {
      return CheckFuncNoCase.forNumber(
          checkFuncNoCase_);
    }

    public Builder clearCheckFuncNo() {
      checkFuncNoCase_ = 0;
      checkFuncNo_ = null;
      onChanged();
      return this;
    }

    private int checkPortfolioIdCase_ = 0;
    private java.lang.Object checkPortfolioId_;
    public CheckPortfolioIdCase
        getCheckPortfolioIdCase() {
      return CheckPortfolioIdCase.forNumber(
          checkPortfolioIdCase_);
    }

    public Builder clearCheckPortfolioId() {
      checkPortfolioIdCase_ = 0;
      checkPortfolioId_ = null;
      onChanged();
      return this;
    }

    private int checkProductIdCase_ = 0;
    private java.lang.Object checkProductId_;
    public CheckProductIdCase
        getCheckProductIdCase() {
      return CheckProductIdCase.forNumber(
          checkProductIdCase_);
    }

    public Builder clearCheckProductId() {
      checkProductIdCase_ = 0;
      checkProductId_ = null;
      onChanged();
      return this;
    }

    private int checkInvestNoCase_ = 0;
    private java.lang.Object checkInvestNo_;
    public CheckInvestNoCase
        getCheckInvestNoCase() {
      return CheckInvestNoCase.forNumber(
          checkInvestNoCase_);
    }

    public Builder clearCheckInvestNo() {
      checkInvestNoCase_ = 0;
      checkInvestNo_ = null;
      onChanged();
      return this;
    }


    /**
     * <pre>
     *功能号
     * </pre>
     *
     * <code>string funcNo = 1;</code>
     */
    public java.lang.String getFuncNo() {
      java.lang.Object ref = "";
      if (checkFuncNoCase_ == 1) {
        ref = checkFuncNo_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (checkFuncNoCase_ == 1) {
          checkFuncNo_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *功能号
     * </pre>
     *
     * <code>string funcNo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFuncNoBytes() {
      java.lang.Object ref = "";
      if (checkFuncNoCase_ == 1) {
        ref = checkFuncNo_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (checkFuncNoCase_ == 1) {
          checkFuncNo_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *功能号
     * </pre>
     *
     * <code>string funcNo = 1;</code>
     */
    public Builder setFuncNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkFuncNoCase_ = 1;
      checkFuncNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *功能号
     * </pre>
     *
     * <code>string funcNo = 1;</code>
     */
    public Builder clearFuncNo() {
      if (checkFuncNoCase_ == 1) {
        checkFuncNoCase_ = 0;
        checkFuncNo_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     *功能号
     * </pre>
     *
     * <code>string funcNo = 1;</code>
     */
    public Builder setFuncNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      checkFuncNoCase_ = 1;
      checkFuncNo_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     *组合id
     * </pre>
     *
     * <code>string portfolioId = 2;</code>
     */
    public java.lang.String getPortfolioId() {
      java.lang.Object ref = "";
      if (checkPortfolioIdCase_ == 2) {
        ref = checkPortfolioId_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (checkPortfolioIdCase_ == 2) {
          checkPortfolioId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *组合id
     * </pre>
     *
     * <code>string portfolioId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPortfolioIdBytes() {
      java.lang.Object ref = "";
      if (checkPortfolioIdCase_ == 2) {
        ref = checkPortfolioId_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (checkPortfolioIdCase_ == 2) {
          checkPortfolioId_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *组合id
     * </pre>
     *
     * <code>string portfolioId = 2;</code>
     */
    public Builder setPortfolioId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkPortfolioIdCase_ = 2;
      checkPortfolioId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *组合id
     * </pre>
     *
     * <code>string portfolioId = 2;</code>
     */
    public Builder clearPortfolioId() {
      if (checkPortfolioIdCase_ == 2) {
        checkPortfolioIdCase_ = 0;
        checkPortfolioId_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     *组合id
     * </pre>
     *
     * <code>string portfolioId = 2;</code>
     */
    public Builder setPortfolioIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      checkPortfolioIdCase_ = 2;
      checkPortfolioId_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     *产品id
     * </pre>
     *
     * <code>string productId = 3;</code>
     */
    public java.lang.String getProductId() {
      java.lang.Object ref = "";
      if (checkProductIdCase_ == 3) {
        ref = checkProductId_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (checkProductIdCase_ == 3) {
          checkProductId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *产品id
     * </pre>
     *
     * <code>string productId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      java.lang.Object ref = "";
      if (checkProductIdCase_ == 3) {
        ref = checkProductId_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (checkProductIdCase_ == 3) {
          checkProductId_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *产品id
     * </pre>
     *
     * <code>string productId = 3;</code>
     */
    public Builder setProductId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkProductIdCase_ = 3;
      checkProductId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *产品id
     * </pre>
     *
     * <code>string productId = 3;</code>
     */
    public Builder clearProductId() {
      if (checkProductIdCase_ == 3) {
        checkProductIdCase_ = 0;
        checkProductId_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     *产品id
     * </pre>
     *
     * <code>string productId = 3;</code>
     */
    public Builder setProductIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      checkProductIdCase_ = 3;
      checkProductId_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     *投顾号
     * </pre>
     *
     * <code>string investNo = 4;</code>
     */
    public java.lang.String getInvestNo() {
      java.lang.Object ref = "";
      if (checkInvestNoCase_ == 4) {
        ref = checkInvestNo_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (checkInvestNoCase_ == 4) {
          checkInvestNo_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *投顾号
     * </pre>
     *
     * <code>string investNo = 4;</code>
     */
    public com.google.protobuf.ByteString
        getInvestNoBytes() {
      java.lang.Object ref = "";
      if (checkInvestNoCase_ == 4) {
        ref = checkInvestNo_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (checkInvestNoCase_ == 4) {
          checkInvestNo_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *投顾号
     * </pre>
     *
     * <code>string investNo = 4;</code>
     */
    public Builder setInvestNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkInvestNoCase_ = 4;
      checkInvestNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *投顾号
     * </pre>
     *
     * <code>string investNo = 4;</code>
     */
    public Builder clearInvestNo() {
      if (checkInvestNoCase_ == 4) {
        checkInvestNoCase_ = 0;
        checkInvestNo_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     *投顾号
     * </pre>
     *
     * <code>string investNo = 4;</code>
     */
    public Builder setInvestNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      checkInvestNoCase_ = 4;
      checkInvestNo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object investDesc_ = "";
    /**
     * <pre>
     *投顾介绍
     * </pre>
     *
     * <code>string investDesc = 5;</code>
     */
    public java.lang.String getInvestDesc() {
      java.lang.Object ref = investDesc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        investDesc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *投顾介绍
     * </pre>
     *
     * <code>string investDesc = 5;</code>
     */
    public com.google.protobuf.ByteString
        getInvestDescBytes() {
      java.lang.Object ref = investDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        investDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *投顾介绍
     * </pre>
     *
     * <code>string investDesc = 5;</code>
     */
    public Builder setInvestDesc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      investDesc_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *投顾介绍
     * </pre>
     *
     * <code>string investDesc = 5;</code>
     */
    public Builder clearInvestDesc() {
      
      investDesc_ = getDefaultInstance().getInvestDesc();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *投顾介绍
     * </pre>
     *
     * <code>string investDesc = 5;</code>
     */
    public Builder setInvestDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      investDesc_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object portfolioName_ = "";
    /**
     * <pre>
     *组合名称
     * </pre>
     *
     * <code>string portfolioName = 6;</code>
     */
    public java.lang.String getPortfolioName() {
      java.lang.Object ref = portfolioName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        portfolioName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *组合名称
     * </pre>
     *
     * <code>string portfolioName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPortfolioNameBytes() {
      java.lang.Object ref = portfolioName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        portfolioName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *组合名称
     * </pre>
     *
     * <code>string portfolioName = 6;</code>
     */
    public Builder setPortfolioName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      portfolioName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *组合名称
     * </pre>
     *
     * <code>string portfolioName = 6;</code>
     */
    public Builder clearPortfolioName() {
      
      portfolioName_ = getDefaultInstance().getPortfolioName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *组合名称
     * </pre>
     *
     * <code>string portfolioName = 6;</code>
     */
    public Builder setPortfolioNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      portfolioName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object portfolioDesc_ = "";
    /**
     * <pre>
     *组合描述
     * </pre>
     *
     * <code>string portfolioDesc = 7;</code>
     */
    public java.lang.String getPortfolioDesc() {
      java.lang.Object ref = portfolioDesc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        portfolioDesc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *组合描述
     * </pre>
     *
     * <code>string portfolioDesc = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPortfolioDescBytes() {
      java.lang.Object ref = portfolioDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        portfolioDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *组合描述
     * </pre>
     *
     * <code>string portfolioDesc = 7;</code>
     */
    public Builder setPortfolioDesc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      portfolioDesc_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *组合描述
     * </pre>
     *
     * <code>string portfolioDesc = 7;</code>
     */
    public Builder clearPortfolioDesc() {
      
      portfolioDesc_ = getDefaultInstance().getPortfolioDesc();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *组合描述
     * </pre>
     *
     * <code>string portfolioDesc = 7;</code>
     */
    public Builder setPortfolioDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      portfolioDesc_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object operatorType_ = "";
    /**
     * <pre>
     *操作类型
     * </pre>
     *
     * <code>string operatorType = 8;</code>
     */
    public java.lang.String getOperatorType() {
      java.lang.Object ref = operatorType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operatorType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *操作类型
     * </pre>
     *
     * <code>string operatorType = 8;</code>
     */
    public com.google.protobuf.ByteString
        getOperatorTypeBytes() {
      java.lang.Object ref = operatorType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operatorType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *操作类型
     * </pre>
     *
     * <code>string operatorType = 8;</code>
     */
    public Builder setOperatorType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      operatorType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *操作类型
     * </pre>
     *
     * <code>string operatorType = 8;</code>
     */
    public Builder clearOperatorType() {
      
      operatorType_ = getDefaultInstance().getOperatorType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *操作类型
     * </pre>
     *
     * <code>string operatorType = 8;</code>
     */
    public Builder setOperatorTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      operatorType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object expireDate_ = "";
    /**
     * <pre>
     *时间
     * </pre>
     *
     * <code>string expireDate = 9;</code>
     */
    public java.lang.String getExpireDate() {
      java.lang.Object ref = expireDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expireDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *时间
     * </pre>
     *
     * <code>string expireDate = 9;</code>
     */
    public com.google.protobuf.ByteString
        getExpireDateBytes() {
      java.lang.Object ref = expireDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        expireDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *时间
     * </pre>
     *
     * <code>string expireDate = 9;</code>
     */
    public Builder setExpireDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      expireDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *时间
     * </pre>
     *
     * <code>string expireDate = 9;</code>
     */
    public Builder clearExpireDate() {
      
      expireDate_ = getDefaultInstance().getExpireDate();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *时间
     * </pre>
     *
     * <code>string expireDate = 9;</code>
     */
    public Builder setExpireDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      expireDate_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ThinkivePortfolioSubmitRequest)
  }

  // @@protoc_insertion_point(class_scope:ThinkivePortfolioSubmitRequest)
  private static final com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest();
  }

  public static com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ThinkivePortfolioSubmitRequest>
      PARSER = new com.google.protobuf.AbstractParser<ThinkivePortfolioSubmitRequest>() {
    @java.lang.Override
    public ThinkivePortfolioSubmitRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ThinkivePortfolioSubmitRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ThinkivePortfolioSubmitRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ThinkivePortfolioSubmitRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lidaifeng.grpc.lib.ThinkivePortfolioSubmitRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

